services:
  server:
    build:
      context: .
    restart: unless-stopped
    container_name: articulate_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_NAME: test
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      DATABASE_HOST: https://mariax-art-mariadb.onrender.com
      DATABASE_PORT: 3306
      DJANGO_SETTINGS_MODULE: articulate.settings
    networks:
      - app-network
    entrypoint: ["/app/entrypoint.sh"]

networks:
  app-network:
    driver: bridge